# Generated by Django 3.1.7 on 2021-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Parentname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('Createpassword', models.CharField(max_length=8)),
                ('Confirmpassword', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Studentname', models.CharField(max_length=30)),
                ('Parentname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('Createpassword', models.CharField(max_length=8)),
                ('Confirmpassword', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=50)),
                ('Createpassword', models.CharField(max_length=8)),
                ('Confirmpassword', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=6)),
                ('YearofPassing', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=50)),
                ('Createpassword', models.CharField(max_length=8)),
                ('Confirmpassword', models.CharField(max_length=8)),
            ],
        ),
    ]
