# Generated by Django 3.1.7 on 2021-03-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Confirmpassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='Confirmpassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Confirmpassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Confirmpassword',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='Createpassword',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='Createpassword',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Createpassword',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Createpassword',
        ),
    ]
